Repository RunningCrew-sns-project/FE, pull requests merged in 2024-10, with the labels that each got.

#3 'mainpageUi'
  .prettierrc
  package-lock.json
  package.json
  src/assets/Font/KBO-Dia-Gothic_bold.woff
  src/assets/Font/KBO-Dia-Gothic_light.woff
  src/assets/Font/KBO-Dia-Gothic_medium.woff
  src/assets/Font/Pretendard-Black.woff
  src/assets/Font/Pretendard-Black.woff2
  src/assets/Font/Pretendard-Bold.woff
  src/assets/Font/Pretendard-Bold.woff2
  src/assets/Font/Pretendard-ExtraBold.woff
  src/assets/Font/Pretendard-ExtraBold.woff2
  src/assets/Font/Pretendard-ExtraLight.woff
  src/assets/Font/Pretendard-ExtraLight.woff2
  src/assets/Font/Pretendard-Light.woff
  src/assets/Font/Pretendard-Light.woff2
  src/assets/Font/Pretendard-Medium.woff
  src/assets/Font/Pretendard-Medium.woff2
  src/assets/Font/Pretendard-Regular.woff
  src/assets/Font/Pretendard-Regular.woff2
  src/assets/Font/Pretendard-SemiBold.woff
  src/assets/Font/Pretendard-SemiBold.woff2
  src/assets/Font/Pretendard-Thin.woff
  src/assets/Font/Pretendard-Thin.woff2
  src/assets/Font/font.css
  src/assets/mianBanner1_bg.jpg
  src/assets/mianBanner2_bg.jpg
  src/assets/mianBanner3_bg.jpg
  src/components/Container.tsx
  src/components/Slider/slider.tsx
  src/hook/usedevice.ts
  src/main.tsx
  src/pages/Main/index.tsx
  src/pages/Main/mainbanner.tsx
  tailwind.config.js
Labels: ✅feat

#4 'bodyBackgroundChage'
  src/components/ThemWrapper.tsx
  src/pages/Runlist/index.tsx
Labels: 🎨ui

#5 'listpageUi'
  index.html
  package-lock.json
  package.json
  src/components/Banner/PathBanner.tsx
  src/components/Container.tsx
  src/components/Modal/Modal.tsx
  src/const/banner.ts
  src/hook/usebanner.tsx
  src/pages/Runlist/Filter/DateFilter.tsx
  src/pages/Runlist/Filter/LocationFilter.tsx
  src/pages/Runlist/ItemList.tsx
  src/pages/Runlist/index.tsx
Labels: 🎨ui

#6 run box
  src/assets/runCrew.jpg
  src/components/RunBox.tsx
  src/pages/MyPage/index.tsx
  src/routes/router.tsx
Labels: 🎨ui

#8 무한 스크롤 컴포넌트
  package-lock.json
  package.json
  src/components/InfiniteScroll.tsx
  src/pages/MyPage/index.tsx
Labels: ✅feat

#9 run box responsive ui
  src/components/InfiniteScroll.tsx
  src/components/RunBox.tsx
  src/pages/MyPage/index.tsx
Labels: 🎨ui

#10 box width custom props
  src/components/RunBox.tsx
  src/pages/MyPage/index.tsx
Labels: 🎨ui

#11 my page ui && runbox ui fix
  src/components/Button.tsx
  src/components/RunBox.tsx
  src/pages/MyPage/MyCrew.tsx
  src/pages/MyPage/MyFeed.tsx
  src/pages/MyPage/MyRunning.tsx
  src/pages/MyPage/index.tsx
  src/routes/router.tsx
Labels: ✅feat, 🎨ui

#12 Blog && imageupload
  package-lock.json
  package.json
  src/App.tsx
  src/api/image/api.ts
  src/components/ApplicationModal.tsx
  src/components/Button.tsx
  src/components/Like/Like.tsx
  src/components/UploadImage.tsx
  src/pages/Blog/Blog.tsx
  src/pages/Blog/BlogCard.tsx
  src/pages/Blog/BlogCardFooter.tsx
  src/pages/Blog/BlogDetail.tsx
  src/pages/Blog/Comment.tsx
  src/pages/Blog/CommentForm.tsx
  src/pages/Blog/WriteBlogCard.tsx
  src/routes/router.tsx
Labels: ✅feat, 🎨ui

#13 my feed layout & profile page layout
  package-lock.json
  src/components/InfiniteScroll.tsx
  src/components/RunBox.tsx
  src/pages/MyPage/MyCrew.tsx
  src/pages/MyPage/MyFeed.tsx
  src/pages/MyPage/MyRunning.tsx
  src/pages/MyPage/Profile.tsx
  src/pages/MyPage/index.tsx
  src/routes/router.tsx
Labels: 🎨ui

#14 fix imageupload
  src/components/UploadImage.tsx
  src/pages/Blog/BlogDetail.tsx
  src/pages/Blog/WriteBlogCard.tsx
Labels: 🔨 fix

#16 Blog ui
  package-lock.json
  src/api/image/api.ts
  src/api/request.ts
  src/components/ApplicationModal.tsx
  src/const/bloginputfields.ts
  src/pages/Blog/Blog.tsx
  src/pages/Blog/BlogCard.tsx
  src/pages/Blog/BlogCardFooter.tsx
  src/pages/Blog/BlogDetail.tsx
  src/pages/Blog/BlogInput.tsx
  src/pages/Blog/Comment.tsx
  src/pages/Blog/CommentForm.tsx
  src/pages/Blog/WriteBlogCard.tsx
  src/pages/MyPage/MyFeed.tsx
Labels: 🔥backend, ✅feat, 🎨ui

#17 detailpage ui
  src/_Mock/list.ts
  src/components/ApplicationModal.tsx
  src/components/RunBox.tsx
  src/pages/Detailpage/DetailHeader.tsx
  src/pages/Detailpage/DetailInfo.tsx
  src/pages/Detailpage/JoinCrewRundetail.tsx
  src/pages/Detailpage/JoinCrewdetail.tsx
  src/pages/Detailpage/JoinRundetail.tsx
  src/pages/MyPage/MyCrew.tsx
  src/pages/Run/commonForm.tsx
  src/pages/Runlist/ItemList.tsx
  src/routes/router.tsx
Labels: ✅feat, 🎨ui
